export const EVENTS = {
  /**
   * EVENTS FIRED AND HANDLED ON THE MAIN ELECTRON APP
   */
  MAIN: {
    CONFIGURATION_UPDATED: "CONFIGURATION_UPDATED",
    TEST: {
      ON_WIKIPEDIA_LOADED: "MAIN_TEST_TEXT_ON_WIKIPEDIA_LOADED"
    },
    USER: {
      LOAD: "MAIN_USER_LOAD",
      ONLOAD: "MAIN_USER_ONLOAD",
      ONUPDATED: "MAIN_USER_ONUPDATED",
      SAVE: "MAIN_USER_SAVE",
      UPDATE: "MAIN_USER_UPDATE"
    }
  },
  /**
   * EVENT FIRED AND HANDLED ON THE UI PROCESS
   */
  RENDERER: {
    TEST: {
      LOAD_WIKIPEDIA: "MAIN_TEST_TEXT_LOAD_WIKIPEDIA"
    }
  }
};

export const CONFIGURATION = {
  LAST_USERNAME: "lastUsername",
  LOG_LEVEL: "logLevel",
  SERVE: "serve",
  SHOW_DEBUG_TOOLS: "showDebugTools",
};

// CULTURE: "culture",
// REMOVE_NON_ASCII_CHAR: "removeNonAsciiChar",
// WIKIPEDIA_URL: "wikipediaUrl",
//   WORD_COUNT: "wordCount"
